add scroll bid search
riwn/shiren2-bot pull request #12
Opened 2021-02-22 00:11 UTC by yushiray

とりあえず分かりやすい巻物で検索機能を実装してみました。
（自分用のdiscardのbotを作ってないので動作未確認）

その他jestでテストの追加とコメントの修正。

2021-02-22 01:21 UTC, riwn commented
わーありがとうございます！
帰ったら動作確認しますね！

2021-02-22 12:19 UTC, riwn requested changes
Command側で動かないことがあったみたいです。
テストは通ってました！

2021-02-22 12:19 UTC, riwn commented on commands/item/SearchBidCommand.js
> +                const item = new Scroll(name);
nameがなくてエラー吐きました。
あと、itemがスコープ外でエラー吐いてたのでその二つを直せば動きました！

2021-02-23 00:12 UTC, yushiray commented
ありがとうございます！
今出先なので戻ったら直しますね。

自分もbotの雛形は作ったのでテスト環境作って確認した方がいいですかね。

2021-02-23 01:52 UTC, riwn commented
https://discord.com/developers/applications
ここのページで作成できますね。
僕はテスト用の鯖作ってそこでテストしてます。

2021-02-23 04:30 UTC, yushiray commented
ありがとうございます。
とりあえずsqlite3の設定ファイルがないよと怒られる以外は直ったかと思います。

2021-02-23 04:33 UTC, riwn commented
確認しました。
動作は確認できましたー
これはmergeしてもいいと思うのですが、

![image](https://user-images.githubusercontent.com/33988894/108802411-8f748d80-75db-11eb-924a-dac07b093784.png)

選んだ値段でアイテムが存在しなかったときの文言追加してもいいかもしれないですね。

2021-02-23 04:40 UTC, riwn approved these changes

2021-02-23 04:47 UTC, yushiray commented
あ、テスト漏れですね。。。
テスト追加してロジック変更したので存在しませんと出るはずです。

2021-02-23 04:59 UTC, riwn commented
確認OKです！
いったんこれでMergeしますね
ちなみに自動デプロイはしてないので本番環境には反映されないです

2021-02-23 04:59 UTC, merged

2021-02-23 07:20 UTC, yushiray commented
ありがとうございます！